# https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-pyproject-toml
[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=63.0",
    "wheel"
]