# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build source distribution and pure-Python wheel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: Get version
        uses: battila7/get-version-action@v2
        id: get_version
      - name: Update version.txt files
        run: |
          echo ${{ steps.get_version.outputs.version-without-v }} > version.txt
      - name: Create package
        id: build
        uses: ExpertaLabs/build-python-dist@main
        with:
          pure_python_wheel: true
          #test_extras: test
          #test_command: python -m pytest tests
          #python-version:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
